# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-07 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20180606_2037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Level',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='role',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_level',
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='login_app.Level'),
        ),
    ]
